// Code generated by generateRoutes.ts
// @generated
////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY. File is AUTO-GENERATED from types.yaml
//
// This file contains type definitions for private/internal types.
// These should NOT be referenced in any externally facing APIs.
//
////////////////////////////////////////////////////////////////////////////

export type ViewCastPushNotificationVariant =
  | 'trending-reengagement'
  | 'affinity-reengagement';

export type PushNotificationTypeVariants = ViewCastPushNotificationVariant;

export type ViewCastPushNotification = {
  id: string;
  type: 'view_cast';
  merkleRoot: string;
  castFid: number;
  castHash: string;
  imageUrl?: string;
  conversationId: string;
  variant?: ViewCastPushNotificationVariant;
};

export type UnreadDirectCastPushNotification = {
  id: string;
  conversationId?: string;
  imageUrl?: string;
  type: 'unread-direct-casts';
};

export type DirectCastIntentPushNotification = {
  id: string;
  conversationId: string;
  counterParties: unknown[];
  intentText: string;
  imageUrl?: string;
  type: 'direct-cast-intent';
};

export type ViewHighlightsPushNotification = {
  id: string;
  type: 'view-highlights';
};

export type ViewForYouUsersPushNotification = {
  id: string;
  type: 'view-for-you-users';
};

export type ViewDiscoverAssetsPushNotification = {
  id: string;
  type: 'view-discover-assets';
};

export type ViewUserProfilePushNotification = {
  id: string;
  type: 'view-user-profile';
  fid: number;
  imageUrl?: string;
  conversationId?: string;
};

export type ViewNotificationsPushNotification = {
  id: string;
  type: 'view-notifications';
};

export type ViewLocationPushNotification = {
  id: string;
  type: 'view-location';
  placeId: string;
  description: string;
};

export type ComposeCastPushNotification = {
  id: string;
  type: 'compose-cast';
  text?: string;
  channelKey?: string;
};

export type ViewExploreChannelsPushNotification = {
  id: string;
  type: 'view-explore-channels';
};

export type ViewConnectedAddressesPushNotification = {
  id: string;
  type: 'view-connected-addresses';
};

export type ViewMutedKeywordsPushNotification = {
  id: string;
  type: 'view-muted-keywords';
};

export type ViewEditLocationPushNotification = {
  id: string;
  type: 'view-edit-location';
};

export type ViewWarpsPushNotification = {
  id: string;
  type: 'view-warps';
};

export type RemoteSiwfRequestNotification = {
  id: string;
  type: 'remote-siwf-request';
  token: string;
};

export type ViewSuperFollowCasts = {
  id: string;
  type: 'view-super-follow-casts';
  notificationGroupId: string;
};

export type DangerouslyTriggerNavigate = {
  id: string;
  type: 'dangerously-trigger-navigate';
  screenName: string;
  screenParams: unknown;
  imageUrl?: string;
  conversationId?: string;
};

export type OpenMiniAppPushNotification = {
  id: string;
  type: 'open-mini-app';
  domain: string;
  imageUrl?: string;
  conversationId?: string;
};

export type NewArticlePushNotification = {
  id: string;
  type: 'new-article';
  articlePublicId: string;
  imageUrl?: string;
  conversationId?: string;
};

export type ActiveBadgePushNotificationAction = 'received' | 'expiring';

export type ActiveBadgePushNotification = {
  id: string;
  type: 'active-badge';
  badgeAction: ActiveBadgePushNotificationAction;
};

export type SyncContactsPushNotification = {
  id: string;
  type: 'sync-contacts';
  fid: number;
};

export type MatchedContactsPushNotification = {
  id: string;
  type: 'matched-contacts';
  imageUrl?: string;
  conversationId?: string;
};

export type ChannelStreakPushNotification = {
  id: string;
  type: 'channel-streak';
  channelKey: string;
};

export type ViewUserBoostInfoPushNotification = {
  id: string;
  type: 'view-user-boost-info';
};

export type ViewCreatorRewardNotification = {
  id: string;
  type: 'view-creator-reward';
  rewardCents: number;
  rewardDate: string;
  txHash: string;
  txChainId: number;
};

export type ViewXPRewardNotification = {
  id: string;
  type: 'view-xp-reward';
  rewardCents: number;
  rewardDate: string;
  xp: number;
};

export type ViewOnrampUpdateNotification = {
  id: string;
  type: 'view-onramp-update';
  uid: string;
  eventType: string;
  txHash?: string;
  chain: string;
  ca: string;
};

export type ViewDeveloperRewardNotification = {
  id: string;
  type: 'view-developer-reward';
};

export type ViewDeveloperRewardEarningNotification = {
  id: string;
  type: 'view-developer-reward-earning';
  domain: string;
  frameName: string;
  frameIconUrl?: string;
  rewardCents: number;
  rewardDate: string;
  txHash: string;
  txChainId: number;
  rank: number;
};

export type ViewDeveloperRewardMissedNotification = {
  id: string;
  type: 'view-developer-reward-missed';
  domain: string;
  frameName: string;
  frameIconUrl?: string;
  rewardCents: number;
  rewardDate: string;
};

export type ViewInvitesLeaderboardRewardNotification = {
  id: string;
  type: 'view-invites-leaderboard-reward';
};

export type ViewInvitesLeaderboardRewardEarningNotification = {
  id: string;
  type: 'view-invites-leaderboard-earning';
  rewardCents: number;
  rewardDate: string;
  txHash: string;
  txChainId: number;
  rank: number;
};

export type ViewInvitesLeaderboardRewardMissedNotification = {
  id: string;
  type: 'view-invites-leaderboard-missed';
  rewardCents: number;
  rewardDate: string;
};

export type ConnectAccountPushNotification = {
  id: string;
  type: 'connect-account';
  platform: 'x' | 'gh' | 'meta' | 'discord' | 'linkedin';
};

export type RecoveryInitiatedPushNotification = {
  id: string;
  type: 'recovery-initiated';
  recoveryId: string;
};

export type TrendingTokenPushNotification = {
  id: string;
  type: 'trending-token';
  chain: string;
  ca: string;
  conversationId?: string;
  imageUrl?: string;
};

export type TrendingFollowRecommendationPushNotification = {
  id: string;
  type: 'trending-follow-recommendation';
  recommendedUsername: string;
  mutualUsername: string;
  mutualTotalCount: number;
  imageUrl?: string;
  conversationId: string;
};

export type FarcasterTipsStartPushNotification = {
  id: string;
  type: 'farcaster-tips-start';
};

export type FarcasterTipsSummaryPushNotification = {
  id: string;
  type: 'farcaster-tips-summary';
};

export type FarcasterTipsEndPushNotification = {
  id: string;
  type: 'farcaster-tips-end';
};

export type WarpsRedemptionOfferPushNotification = {
  id: string;
  type: 'warps-redemption-offer';
};

export type WalletActivityPushNotification = {
  id: string;
  type: 'wallet-activity';
  chain: string;
  hash: string;
  imageUrl?: string;
  conversationId: string;
};

export type TipReceivedPushNotification = {
  id: string;
  type: 'tip-received';
  tipId: string;
  imageUrl?: string;
  conversationId?: string;
};

export type NewFarcasterProSubscriptionPushNotification = {
  id: string;
  type: 'farcaster-pro-subscription-communication';
  conversationId?: string;
  redirectTo: 'trade-ideas' | 'upsell';
};

export type OnrampUpdatePushNotification = {
  id: string;
  type: 'onramp-update';
  transactionId: string;
  txHash?: string;
  chain: string;
  ca: string;
  conversationId: string;
};

export type NewCampaignPushNotification = {
  id: string;
  type: 'new-campaign';
};

export type TokenAlertPushNotification = {
  id: string;
  type: 'token-alert';
  chain: string;
  ca: string;
  conversationId?: string;
  imageUrl?: string;
};

export type TraderAlertPushNotification = {
  id: string;
  type: 'trader-alert';
  chain: string;
  ca: string;
  conversationId?: string;
  imageUrl?: string;
};

export type ReferralCodeClaimedPushNotification = {
  id: string;
  type: 'referral-code-claimed';
  conversationId?: string;
  imageUrl?: string;
};

export type ReferralLaunchPushNotification = {
  id: string;
  type: 'referral-launch';
};

export type ReferralReminderPushNotification = {
  id: string;
  type: 'referral-reminder';
};

export type XpRewardExpireSoonPushNotification = {
  id: string;
  type: 'xp-reward-expire-soon';
};

export type XpRewardExpireImminentPushNotification = {
  id: string;
  type: 'xp-reward-expire-imminent';
};

export type DepositBonusesLaunchPushNotification = {
  id: string;
  type: 'deposit-bonuses-launch';
};

export type DepositBonusesIneligiblePushNotification = {
  id: string;
  type: 'deposit-bonuses-ineligible';
};

export type SwapFailedPushNotification = {
  id: string;
  type: 'swap-failed';
  sellChain: string;
  sellCa: string;
  buyChain: string;
  buyCa: string;
  sellAmount: string;
  imageUrl?: string;
  conversationId?: string;
};

export type LimitOrderMatchedPushNotification = {
  id: string;
  type: 'limit-order-matched';
  limitOrderId: string;
  kind: 'sell' | 'buy';
  sellChain: string;
  sellCa: string;
  buyChain: string;
  buyCa: string;
  sellAmount: string;
  buyAmount: string;
  isPartialFill: boolean;
  imageUrl?: string;
  conversationId?: string;
};

export type UsdcLendingPushNotification = {
  id: string;
  type: 'usdc-lending';
};

export type AudioRoomLivePushNotification = {
  id: string;
  type: 'audio-room-live';
  roomId: string;
  imageUrl?: string;
  conversationId?: string;
};

export type AudioRoomScheduledStartPushNotification = {
  id: string;
  type: 'audio-room-scheduled-start';
  roomId: string;
  imageUrl?: string;
};

export type AudioRoomHandRaisedPushNotification = {
  id: string;
  type: 'audio-room-hand-raised';
  roomId: string;
  raiserFid: number;
  imageUrl?: string;
};

export type AudioRoomInviteToStagePushNotification = {
  id: string;
  type: 'audio-room-invite-to-stage';
  roomId: string;
  inviterFid: number;
  role: 'host' | 'cohost' | 'speaker' | 'listener';
  imageUrl?: string;
};

export type PushNotificationPayload =
  | ViewCastPushNotification
  | UnreadDirectCastPushNotification
  | DirectCastIntentPushNotification
  | ViewHighlightsPushNotification
  | ViewForYouUsersPushNotification
  | ViewDiscoverAssetsPushNotification
  | ViewUserProfilePushNotification
  | ViewNotificationsPushNotification
  | ViewLocationPushNotification
  | ComposeCastPushNotification
  | ViewExploreChannelsPushNotification
  | ViewConnectedAddressesPushNotification
  | ViewMutedKeywordsPushNotification
  | ViewEditLocationPushNotification
  | ViewWarpsPushNotification
  | ViewSuperFollowCasts
  | DangerouslyTriggerNavigate
  | OpenMiniAppPushNotification
  | ActiveBadgePushNotification
  | SyncContactsPushNotification
  | MatchedContactsPushNotification
  | ChannelStreakPushNotification
  | ViewUserBoostInfoPushNotification
  | ViewCreatorRewardNotification
  | ViewXPRewardNotification
  | ViewDeveloperRewardNotification
  | ViewDeveloperRewardEarningNotification
  | ViewDeveloperRewardMissedNotification
  | ConnectAccountPushNotification
  | RemoteSiwfRequestNotification
  | RecoveryInitiatedPushNotification
  | TrendingTokenPushNotification
  | TrendingFollowRecommendationPushNotification
  | FarcasterTipsStartPushNotification
  | FarcasterTipsSummaryPushNotification
  | FarcasterTipsEndPushNotification
  | WarpsRedemptionOfferPushNotification
  | WalletActivityPushNotification
  | TipReceivedPushNotification
  | ViewInvitesLeaderboardRewardNotification
  | ViewInvitesLeaderboardRewardEarningNotification
  | ViewInvitesLeaderboardRewardMissedNotification
  | NewCampaignPushNotification
  | TokenAlertPushNotification
  | TraderAlertPushNotification
  | ReferralCodeClaimedPushNotification
  | ReferralLaunchPushNotification
  | ReferralReminderPushNotification
  | XpRewardExpireSoonPushNotification
  | XpRewardExpireImminentPushNotification
  | DepositBonusesLaunchPushNotification
  | NewArticlePushNotification
  | DepositBonusesIneligiblePushNotification
  | OnrampUpdatePushNotification
  | NewFarcasterProSubscriptionPushNotification
  | SwapFailedPushNotification
  | LimitOrderMatchedPushNotification
  | UsdcLendingPushNotification
  | AudioRoomLivePushNotification
  | AudioRoomScheduledStartPushNotification
  | AudioRoomHandRaisedPushNotification
  | AudioRoomInviteToStagePushNotification;

export type DirectCastsConversationMessagesCursor = {
  page: number;
  limit: number;
  before?: number;
  after?: number;
  midpoint?: number;
};

export type CreateAuthTokenRequest = {
  method: 'generateToken';
  params: {
    timestamp: number;
    expiresAt?: number;
  };
};
